#!/bin/sh
#
# 2020-2025 Garmin Ltd. or its subsidiaries
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# check if the script is sourced or executed and get the script name
is_sourced=1
THIS_SCRIPT=""
if [ -n "$ZSH_VERSION" ]; then
	THIS_SCRIPT="$0"
	case "$ZSH_EVAL_CONTEXT" in 
		*:file:*) is_sourced=0;;
	esac
elif [ -n "$BASH_VERSION" ]; then
	#shellcheck disable=SC3054,SC3028
	THIS_SCRIPT="${BASH_SOURCE[0]}"
	if [ "$THIS_SCRIPT" = "$0" ]; then
		is_sourced=0
	fi
else
	echo "Unknown shell. Assuming this script is sourced."
	THIS_SCRIPT="init-build-env"
fi

if [ $is_sourced -eq 0 ]; then
	echo "Error: This script needs to be sourced. Please run as '. $THIS_SCRIPT'"
	exit 1
fi

if [ -z "$WHISK_ROOT" ]; then
	WHISK_ROOT=$(dirname "$(readlink -f "$THIS_SCRIPT")")
	if [ -z "$WHISK_ROOT" ]; then
		WHISK_ROOT="$(pwd)"
	fi
fi

if [ -z "$WHISK_CONF" ]; then
	WHISK_CONF="$(readlink -f "$(dirname $THIS_SCRIPT)")/whisk.yaml"
fi

whisk_cleanup() {
	unset whisk_cleanup WHISK_EXTRA_CONF
}

configure() {
	tmp_env_file=$(mktemp -t whisk-env.XXXXXX)

	"$WHISK_ROOT/bin/whisk" configure \
			--env "$tmp_env_file" \
			--conf "$WHISK_CONF" \
			"$WHISK_EXTRA_CONF" \
			-- "$@"
	ERR=$?

	if [ "$WHISK_CAPTURE_ENV" = "-" ]; then
		cat "$tmp_env_file"
	elif [ -n "$WHISK_CAPTURE_ENV" ]; then
		cat "$tmp_env_file" > "$WHISK_CAPTURE_ENV"
	fi

	if [ $ERR != 0 ]; then
		rm "$tmp_env_file"
		return $ERR
	fi

	#shellcheck disable=SC1090
	. "$tmp_env_file"
	rm "$tmp_env_file"
	return 0
}

if ! WHISK_EXTRA_CONF="--init" configure "$@"; then
	whisk_cleanup
	return 1
fi

whisk_cleanup
# vim: noexpandtab
