#! /bin/sh
#
# 2020 Garmin Ltd. or its subsidiaries
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

THIS_DIR="$(dirname $0)"

cd $THIS_DIR

REV="$(git rev-parse HEAD):$(shasum "requirements.txt")"

if [ ! -e "venv/rev.txt" ] || [ "$(cat venv/rev.txt)" != "$REV" ]; then
    python3 -m venv "venv"
    . "venv/bin/activate"
    pip install -U pip
    pip install -r requirements.txt
    echo "$REV" > "venv/rev.txt"
fi

