#! /bin/sh
#
# 2020 Garmin Ltd. or its subsidiaries
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

THIS_DIR="$(dirname $0)"
VENV_DIR="$THIS_DIR/venv"

cd $THIS_DIR

REV="$(git rev-parse HEAD):$(shasum "requirements.txt")"

if [ ! -e "$VENV_DIR/rev.txt" ] || [ "$(cat $VENV_DIR/rev.txt)" != "$REV" ]; then
    set +eu
    python3 -m venv "$VENV_DIR"
    . "$VENV_DIR/bin/activate"
    pip install -r requirements.txt
    echo "$REV" > "$VENV_DIR/rev.txt"
fi

