#! /bin/sh
#
# 2020 Garmin Ltd. or its subsidiaries
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

if [ -z "$1" ]; then
    echo "Usage: $0 WHISK_CONF_FILE"
    exit 1
fi

THIS_DIR="$(dirname $0)"

export PIPENV_PIPFILE="$THIS_DIR/Pipfile"

pipenv sync --bare

pipenv run -- python - "$1" "$THIS_DIR/whisk.schema.json" <<HEREDOC
import json
import jsonschema
import sys
import yaml

try:
    with open(sys.argv[1], "r") as f, open(sys.argv[2], "r") as schema:
        jsonschema.validate(
            yaml.load(f, Loader=yaml.Loader),
            json.load(schema)
        )
except jsonschema.ValidationError as e:
    print(e)
    sys.exit(1)
HEREDOC

pipenv run -- yamllint -s "$1"

